### ISSUE TITLE
Exception when trying to generate configuration with CACHE_TIMEOUT=0

### ISSUE THREAD

**Issue by smaxx1337** [respawner/peering-manager#262] opened 2020-06-25 11:44 UTC
### Environment
* Python version:  3.6.8
* Peering Manager version:  master

### Steps to Reproduce
1. Go to your router

2. Press "Configuration" to generate config

### Expected Behavior

Getting a configuration

### Observed Behavior

```
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'redis.exceptions.ResponseError'>
invalid expire time in setex
```
![image](https://user-images.githubusercontent.com/8495515/85713018-37eaee80-b6e9-11ea-9bbe-ef8bf3a32c66.png)

Redis is running:
```
systemctl status redis
● redis.service - Redis persistent key-value database
   Loaded: loaded (/usr/lib/systemd/system/redis.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/redis.service.d
           └─limit.conf
   Active: active (running) since Thu 2020-06-25 13:32:14 CEST; 6min ago
```

I'm running Peering-Manager with systemd. There are no errors in the logs, anywhere.

When I try to set "DEBUG = True" in the configuration.py, I can not start peering-manager anymore:
```
# /opt/peering-manager/venv/bin/gunicorn --pid /var/tmp/peering-manager.pid --pythonpath /opt/peering-manager --config /opt/peering-manager/gunicorn_config.py peering_manager.wsgi
[2020-06-25 13:41:19 +0200] [25093] [INFO] Starting gunicorn 20.0.4
[2020-06-25 13:41:19 +0200] [25093] [INFO] Listening at: http://127.0.0.1:8002 (25093)
[2020-06-25 13:41:19 +0200] [25093] [INFO] Using worker: threads
[2020-06-25 13:41:19 +0200] [25096] [INFO] Booting worker with pid: 25096
[2020-06-25 13:41:20 +0200] [25097] [INFO] Booting worker with pid: 25097
[2020-06-25 13:41:20 +0200] [25100] [INFO] Booting worker with pid: 25100
[2020-06-25 13:41:20 +0200] [25101] [INFO] Booting worker with pid: 25101
[2020-06-25 13:41:20 +0200] [25102] [INFO] Booting worker with pid: 25102
Traceback (most recent call last):
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/peering-manager/venv/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/opt/peering-manager/venv/lib64/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

```
As soon as I remove the DEBUG = True, it works again.

**Comment by respawner** [comment] 2020-06-25 20:11
What is the value of the `CACHE_TIMEOUT` setting?

**Comment by smaxx1337** [comment] 2020-06-26 14:06
my Redis configuration in the configuration.py looks like this:
```
REDIS = {
    'HOST': 'localhost',
    'PORT': 6379,
    'PASSWORD': '',
    'CACHE_DATABASE': 1,
    'DEFAULT_TIMEOUT': 300,
    'SSL': False,
}
```
So according to the docs CACHE_TIMEOUT should be 0, I think
https://peering-manager.readthedocs.io/en/latest/configuration/optional-settings/#redis

**Comment by respawner** [comment] 2020-06-26 14:14
If you want to disable caching, it is to be set to `0` indeed. However I did not perform a check for a `0` value [here](https://github.com/respawner/peering-manager/blob/b5fe047f378903ea1062fa7536955c550d944da9/peering/models.py#L1533) so it may be the cause of this issue.

**Comment by smaxx1337** [comment] 2020-06-29 07:15
Yup, CACHE_TIMEOUT at 0 is the issue here.
I have set it to 900 now and generating a configuration works again. Thank you!

**Comment by respawner** [comment] 2020-06-29 07:26
Lets leave the issue opened, until a fix has been commited.

**Closed** 2020-07-06 20:43 UTC
Labels: type: bug
